### ISSUE TITLE
https://github.com/coder-smookki/DOOM-1993/tree/main

### ISSUE THREAD

**Issue by coder-smookki** [Rblba20/pseudo-doom#1]
**Может ты всё таки оставишь звёздочку на мой проект?)
Ты же используешь некоторые элементы моего проекта)**

**Comment by Rblba20** [comment]
Без проблем. Добавил.
Пойдет?

**Comment by coder-smookki** [comment]
> Без проблем. Добавил. Пойдет?

Ну это тоже можно. Я про то, что ты бы дал лучше звёздочку репозиторию с Doom на python)

**Comment by coder-smookki** [comment]
Но всё равно. Благодарю!
Классный репозиторий!)

**Comment by Rblba20** [comment]
> > Без проблем. Добавил. Пойдет?
> 
> Ну это тоже можно. Я про то, что ты бы дал лучше звёздочку репозиторию с Doom на python)

Не так понял изначально, но звездочку добавил

**Comment by coder-smookki** [comment]
> > > Без проблем. Добавил. Пойдет?
> > 
> > 
> > Ну это тоже можно. Я про то, что ты бы дал лучше звёздочку репозиторию с Doom на python)
> 
> Не так понял изначально, но звездочку добавил

Благодарю!
